### ISSUE TITLE
Adding a Code of Conduct file

### ISSUE THREAD

**Issue by shikharcodes** [YashKumarVerma/github-spy#5]
Hey @YashKumarVerma , while looking at this project I noticed that the Code of Conduct file is missing.
I would like to add this if you want. Please assign me this under SWoC2021 label.

**Comment by shikharcodes** [comment]
@YashKumarVerma where can I contact you regarding any doubts or communication?

**Comment by YashKumarVerma** [comment]
Feel free to open an issue regarding the doubts you have @shikharcodes

**Comment by shikharcodes** [comment]
I couldn't find any contact us email id mentioned here in the project. So what contact email should I add in the file @YashKumarVerma ?
Also just wanted to confirm that have you linked this issue with SWoC since I'm a participant in that?

**Comment by YashKumarVerma** [comment]
yeah, this is part of swoc. mention my email id `yk.verma2000@gmail.com` if needed anywhere.

**Comment by shikharcodes** [comment]
Also, should it address to maintainers or maintainer, i.e. you maintain the project alone or there are others too?

**Comment by YashKumarVerma** [comment]
`maintainers` because there would be more than one maintainer.

**Comment by shikharcodes** [comment]
I've added the file @YashKumarVerma. Please review and merge.

**Comment by YashKumarVerma** [comment]
done:)

**Comment by shikharcodes** [comment]
Thanks, @YashKumarVerma :), can you close this issue too, please?

**Comment by shikharcodes** [comment]
> done:)

Hey, @YashKumarVerma have you sent project status to SWoC team so that my points can be synced to the SWoC leaderboard?
