### ISSUE TITLE
Readme beautification

### ISSUE THREAD

**Issue by Sloth-Panda** [YashKumarVerma/github-spy#9]
Let me know if this needs to be beautified

**Comment by YashKumarVerma** [comment]
sure, what are your suggestions for improvements ?

**Comment by Sloth-Panda** [comment]
1. links to code of conduct and contributing file
2.  adding emojis beside the main describing words of readme
3.  adding one open-source section  that ur project's a part of
4.  may be also include some gifs (memes) (optional if you want it let me know)
These are the proposed changes let me know

**Comment by YashKumarVerma** [comment]
sure, send PR.
